---
- name: Prepare
  hosts: all
  connection: local
  become: true

  tasks:
    - name: Update apt cache (Debian)
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Install git
      package:
        name: git
        state: present

    - name: Clone dotfiles repo (HTTPS)
      git:
        repo: https://github.com/coaxial/dotfiles.git
        dest: "{{ ansible_env.HOME }}/dotfiles"

    - name: Remove git
      package:
        name: git
        state: absent

    - name: Install fontconfig package (for tests)
      package:
        name: fontconfig
        state: present
