---
- hosts: all
  connection: local
  become: true
  tasks:
    - include_tasks: tasks/set_env.yml
    - include_tasks: tasks/ssh_key.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/fonts.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/nvim.yml
    - include_tasks: tasks/ruby.yml

  handlers:
    - include: handlers/ssh.yml
