---
- hosts: all
  connection: local
  become: false
  tasks:
    - name: Update apt cache (Debian)
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - include_tasks: tasks/set_env.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/fonts.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/nvim.yml
    - include_tasks: tasks/rvm.yml
    - include_tasks: tasks/nvm.yml
    - include_tasks: tasks/backups.yml
    # TODO: ssh config and other postinstall

  handlers:
    - include: handlers/ssh.yml
