---
- name: Create config dir
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.config"
    mode: 0700
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Backup existing .bashrc and .profile
  shell: 'if [ ! -L "$HOME/{{ item }}" ]; then mv "$HOME/{{ item }}" "$HOME/{{ item }}.bak"; fi'
  with_items:
    - .bashrc
    - .profile
  changed_when: false
  failed_when: false

- name: Symlink config files
  file:
    state: link
    src: "{{ df__repo_location }}/ansible-playbook/files/home/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
  with_items:
    - .ansible.cfg
    - .asciinema
    - .bash_aliases
    - .bash_prompt
    - .bashrc
    - .config/nvim
    - .config/borgmatic
    - .config/kitty
    - .gemrc
    - .ghc
    - .gitconfig
    - .gitignore_global
    - .gvimrc
    - .irssi
    - .maid
    - .path
    - .profile
    - .tmux.conf
    - .vimrc
